### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by whyrusleeping** [haadcode/orbit-core#1]
```
[ npm install output.....]

> orbit_@0.1.0-beta.1 test /home/whyrusleeping/code/orbit-core
> LOG=none ./node_modules/.bin/mocha



  Orbit with js-ipfs-api
    1) "before all" hook

  0 passing (3s)
  1 failing

  1) Orbit with js-ipfs-api "before all" hook:
     Error: non-zero exit code 1
  while running: /home/whyrusleeping/code/orbit-core/node_modules/subcomandante/subcom 22100 /home/whyrusleeping/code/orbit-core/node_modules/@haad/go-ipfs-dep/go-ipfs/ipfs daemon --enable-pubsub-experiment

  Error: serveHTTPApi: manet.Listen(/ip4/127.0.0.1/tcp/5001) failed: listen tcp4 127.0.0.1:5001: bind: address already in use

      at ChildProcess.<anonymous> (node_modules/subcomandante/fork.js:21:23)
      at maybeClose (internal/child_process.js:885:16)
      at Socket.<anonymous> (internal/child_process.js:334:11)
      at Pipe._handle.close [as _onclose] (net.js:501:12)




npm ERR! Linux 4.8.7-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "test"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! orbit_@0.1.0-beta.1 test: `LOG=none ./node_modules/.bin/mocha`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the orbit_@0.1.0-beta.1 test script 'LOG=none ./node_modules/.bin/mocha'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the orbit_ package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     LOG=none ./node_modules/.bin/mocha
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs orbit_
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls orbit_
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/whyrusleeping/code/orbit-core/npm-debug.log
make: *** [Makefile:8: test] Error 1

```

**Comment by haadcode** [comment]
Fixed in master
